### ISSUE TITLE
Access to count matrices

### ISSUE THREAD

**Issue by ChristophH** [LiZhaoLab/2019_Dmel_testis_singlecell#3]
Hello,
I enjoyed reading the paper and would like to use the data for method development. Could you provide the (fixed) cellranger output (filtered count matrices) so I wouldn't have to start with the raw reads? What I'm interested in are the contents of the 180731_517_novogene/outs/filtered_gene_bc_matrices/180731_dmel_testis_AG_mergedref_FBgn/ directory of your pipeline. 
Thank you,
Christoph

**Comment by ewitt1093** [comment]
Hi Christoph, 
The count matrices are too big to put on github, but here is a link in Box.
https://rockefeller.box.com/s/m04qx1qf0c9naaptxlkljvhsnl464gjo
-Evan

**Comment by ChristophH** [comment]
Thank you!
